// [LAYER: CORE]
/**
 * Canonical Spider agent-ergonomics surface — both GraphCapability.spider and AuditCapability.spider
 * must expose these methods for alternate-entry parity.
 */
export const SPIDER_AGENT_ERGONOMICS_METHODS = [
  'audit',
  'gate',
  'gateBundle',
  'check',
  'checkAndRespond',
  'runCheckPipeline',
  'runAgentScenario',
  'runAgentScenarioAndRespond',
  'bundle',
  'validateBundle',
  'batchPreflight',
  'preflight',
  'preflightBundle',
  'setBaseline',
  'compareBaseline',
  'compareBaselineBundle',
  'sessionDelta',
  'shouldProceed',
  'toolSchema',
  'outputSchema',
  'handoff',
  'handoffFromCheck',
  'buildCiArtifacts',
  'buildScenarioCiArtifacts',
  'writeCiArtifacts',
  'writeScenarioCiArtifacts',
  'serializeBundle',
  'parseBundleWire',
  'validateWire',
  'validateWireRestore',
  'restoreFromWire',
  'getWireOutputSchema',
  'parseNdjsonStream',
  'formatWireDigest',
  'formatCheckDigest',
  'formatPreflightDigest',
  'toCheckResponse',
  'toScenarioResponse',
  'toScenarioNdjsonStream',
  'parseScenarioNdjsonStream',
  'formatScenarioFailure',
  'formatCheckFailure',
  'formatPipelineFailure',
  'formatFailureFromCheck',
  'formatFailureFromScenario',
  'getFailureOutputSchema',
  'validateFailureEnvelope',
  'safeValidateFailureEnvelope',
  'isFailureEnvelope',
  'parseFailureJson',
  'toFailureNdjsonStream',
  'parseFailureNdjsonStream',
  'toGithubCheckRunFromFailure',
  'getCheckOutputSchema',
  'getScenarioOutputSchema',
  'getCheckInputSchema',
  'getPipelineInputSchema',
  'getSchemaRegistry',
  'normalizeCheckRequest',
  'getAgentScenarios',
  'recommendCheckRequest',
  'formatAgentDecisionGuide',
  'getWorkflowPresets',
  'safeValidateCheckRequest',
  'validateCheckPipelineRequest',
  'safeValidateCheckPipelineRequest',
  'prepareSarifUpload',
  'buildDiagnosticSummary',
  'validateCheck',
  'validateCheckResponse',
  'safeValidateCheckResponse',
  'isCheckResponse',
  'parseCheckResponseJson',
  'assertCheckPassed',
  'assertCheckFailed',
  'assertScenarioPassed',
  'assertScenarioFailed',
  'validateScenario',
  'validateScenarioResponse',
  'writeSchemaRegistry',
  'getAgentMethodGroups',
  'toCheckNdjsonStream',
  'toGithubCheckRun',
  'getProblemMatcherConfig',
  'getAgentToolkitCatalog',
  'formatCatalogPrompt',
  'getAgentRunbook',
  'getMcpToolNames',
  'validateCheckRequest',
  'getGatePolicyPresets',
  'toStructuredTelemetry',
  'agentContext',
  'applyBundleBudget',
  'compact',
  'toSarif',
  'toLspDiagnostics',
  'toDiagnosticJson',
  'toGithubAnnotations',
  'toTap',
  'toJUnitXml',
  'toNdjson',
  'formatDiffNarrative',
  'diffSinceLast',
  'diff',
  'explain',
  'explainForAgent',
  'formatNarrative',
  'resync',
] as const;

export type SpiderAgentErgonomicsMethod = (typeof SPIDER_AGENT_ERGONOMICS_METHODS)[number];

/** Grouped agent surface — mirrors OpenAPI tags and rust-analyzer command categories. */
export const SPIDER_AGENT_METHOD_GROUPS = {
  unified: [
    'check',
    'checkAndRespond',
    'runCheckPipeline',
    'runAgentScenario',
    'runAgentScenarioAndRespond',
  ],
  validation: [
    'validateCheckRequest',
    'validateCheckPipelineRequest',
    'safeValidateCheckRequest',
    'safeValidateCheckPipelineRequest',
    'validateCheck',
    'validateCheckResponse',
    'safeValidateCheckResponse',
    'validateScenario',
    'validateBundle',
    'validateWire',
    'validateWireRestore',
    'validateFailureEnvelope',
    'safeValidateFailureEnvelope',
  ],
  schemas: [
    'getCheckInputSchema',
    'getCheckOutputSchema',
    'getPipelineInputSchema',
    'getScenarioOutputSchema',
    'getFailureOutputSchema',
    'getSchemaRegistry',
    'getWireOutputSchema',
    'writeSchemaRegistry',
  ],
  formats: [
    'toCheckResponse',
    'toScenarioResponse',
    'toCheckNdjsonStream',
    'toScenarioNdjsonStream',
    'toFailureNdjsonStream',
    'parseFailureNdjsonStream',
    'toGithubCheckRun',
    'toGithubCheckRunFromFailure',
    'toSarif',
    'toLspDiagnostics',
    'toTap',
    'toJUnitXml',
    'toNdjson',
    'formatCheckDigest',
    'formatScenarioFailure',
    'formatCheckFailure',
    'formatPipelineFailure',
    'formatFailureFromCheck',
    'formatFailureFromScenario',
  ],
  catalog: [
    'getAgentToolkitCatalog',
    'formatCatalogPrompt',
    'formatAgentDecisionGuide',
    'getAgentScenarios',
    'recommendCheckRequest',
    'getAgentMethodGroups',
    'getMcpToolNames',
  ],
} as const;

export function getAgentMethodGroups() {
  return SPIDER_AGENT_METHOD_GROUPS;
}

/** Graph-only structural ops — not required on AuditCapability.spider. */
export const SPIDER_GRAPH_ONLY_METHODS = [
  'bootstrapGraph',
  'applyChanges',
  'auditStructure',
  'verifyGraphIntegrity',
  'getStudyPack',
] as const;
